version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build:
      context: ./django/
    command: sh /code/entrypoint.sh
    volumes:
      - ./django/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  client:
    build:
      context: ./frontend/
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

volumes:
  postgres_data:
